[project]
name = "cppport"
version = "0.0.1"
requires-python = ">=3.11"

[project.scripts]
cppport = "cppport.cli:main"

[project.optional-dependencies]
dev = [
"pytest",
"pytest-cov",
"ruff",
"build",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
